'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { AdminNav } from '@/components/admin-nav';
import { adminFetch } from '@/lib/admin-api';

type Detail = { id:string; publicId:string; category:string; name:string; phone:string; regionLevel1:string; regionLevel2?:string; preferredPlace?:string; preferredContactTime?:string; inquiry:string; status:string; privacyConsentVersion:string; privacyConsentAt:string; retentionExpiresAt:string; createdAt:string; notes:{id:string;content:string;author:string;createdAt:string}[]; contacts:{id:string;type:string;result?:string;contactedAt:string;admin:string}[] };
const statuses = [['NEW','신규'],['CONTACT_SCHEDULED','연락 예정'],['CONTACTED','연락 완료'],['APPOINTMENT_BOOKED','상담 예약'],['COMPLETED','상담 완료'],['CONTRACT_IN_PROGRESS','계약 진행'],['CLOSED','종결'],['UNREACHABLE','연락 불가'],['PENDING_DELETION','삭제 예정']];

export default function ConsultationDetailPage() {
  const { id } = useParams<{ id:string }>(); const router = useRouter(); const [item,setItem]=useState<Detail>(); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setItem(await adminFetch(`/admin/consultations/${id}`));}catch(e){setError(e instanceof Error?e.message:'조회 오류');}},[id]); useEffect(()=>{void load();},[load]);
  async function status(value:string){await adminFetch(`/admin/consultations/${id}/status`,{method:'PATCH',body:JSON.stringify({status:value})});await load();}
  async function note(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const content=new FormData(form).get('content');await adminFetch(`/admin/consultations/${id}/notes`,{method:'POST',body:JSON.stringify({content})});form.reset();await load();}
  async function contact(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);await adminFetch(`/admin/consultations/${id}/contacts`,{method:'POST',body:JSON.stringify({type:d.get('type'),result:d.get('result'),contactedAt:new Date().toISOString()})});form.reset();await load();}
  async function remove(){if(!confirm('이 상담과 메모·연락 이력을 영구 삭제할까요?'))return;await adminFetch(`/admin/consultations/${id}`,{method:'DELETE'});router.push('/admin/consultations');}
  return <><AdminNav/><main className="admin-main container">{error&&<p className="form-error">{error}</p>}{item&&<><div className="admin-title"><div><p className="eyebrow">{item.publicId}</p><h1>{item.name}님의 상담</h1></div><select value={item.status} onChange={e=>void status(e.target.value)}>{statuses.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="detail-grid"><section className="admin-panel"><h2>신청 정보</h2><dl><dt>전화번호</dt><dd><a href={`tel:${item.phone}`}>{item.phone}</a></dd><dt>상담 분야</dt><dd>{item.category}</dd><dt>희망 지역</dt><dd>{[item.regionLevel1,item.regionLevel2,item.preferredPlace].filter(Boolean).join(' ')}</dd><dt>연락 희망 시간</dt><dd>{item.preferredContactTime||'언제든 가능'}</dd><dt>접수일</dt><dd>{new Date(item.createdAt).toLocaleString('ko-KR')}</dd><dt>동의</dt><dd>{item.privacyConsentVersion} / {new Date(item.privacyConsentAt).toLocaleString('ko-KR')}</dd><dt>파기 예정일</dt><dd>{new Date(item.retentionExpiresAt).toLocaleDateString('ko-KR')}</dd></dl><h3>상담 내용</h3><p className="inquiry">{item.inquiry}</p></section><aside><section className="admin-panel"><h2>내부 메모</h2><form onSubmit={note}><textarea name="content" rows={3} required maxLength={2000}/><button className="button button-small">메모 추가</button></form><div className="timeline">{item.notes.map(n=><article key={n.id}><p>{n.content}</p><small>{n.author} · {new Date(n.createdAt).toLocaleString('ko-KR')}</small></article>)}</div></section><section className="admin-panel"><h2>연락 이력</h2><form onSubmit={contact}><select name="type"><option value="CALL">전화</option><option value="SMS">문자</option><option value="EMAIL">이메일</option><option value="MEETING">미팅</option></select><input name="result" placeholder="연락 결과" maxLength={500}/><button className="button button-small">이력 추가</button></form><div className="timeline">{item.contacts.map(c=><article key={c.id}><strong>{c.type}</strong><p>{c.result||'-'}</p><small>{c.admin} · {new Date(c.contactedAt).toLocaleString('ko-KR')}</small></article>)}</div></section><button className="danger-button" onClick={()=>void remove()}>상담 영구 삭제</button></aside></div></>}</main></>;
}

